const language = {
    
    hindi: {
        title: 'सब ब्रोकर बनें',
        namelbl: 'नाम',
        moblbl: 'मोबाइल नंबर',
        emaillbl: 'ईमेल',
        citylbl: 'शहर का चयन करें',
        statelbl: 'राज्य खोजें',
        namelblerror1: 'अमान्य नाम',
        namelblerror2: 'अपना नाम दर्ज करें',
        moblblerror1: 'अमान्य मोबाइल नंबर',
        moblblerror2: '10 अंकों का मोबाइल नंबर दर्ज करें',
        emaillblerror1: 'अपना ईमेल दर्ज करें',
        emaillblerror2: 'अमान्य ईमेल',
        citylblerror1: 'शहर का चयन आवश्यक है',
        statelblerror1: 'राज्य का चयन आवश्यक है',
        sendotpbtn: 'OTP भेजें',
        termstitle: 'ध्यान दें',
        termscontent: 'हम यह डेटा केवल संचार के उद्देश्य से ले रहे हैं और इसे सुरक्षित रूप से संग्रहीत किया जाएगा। हम आपकी गोपनीयता की रक्षा के लिए प्रतिबद्ध हैं, इससे सहमत होकर आप हमें एसएमएस/व्हाट्सएप/ईमेल/कॉल के माध्यम से अपडेट भेजने की अनुमति दे रहे हैं और इसे डीएनडी का उल्लंघन नहीं कहा जाएगा।',
        termsbtn: 'ठीक है',
        otppopuptitle: 'कृपया अपना मोबाइल नंबर सत्यापित करने के लिए ओटीपी दर्ज करें',
        otppopupinfo: 'ओटीपी भेज दिया गया है',
        otppopuptimeremaining: 'ओटीपी फिर से भेजें:',
        otppopupbtn: 'सत्यापित करें',
        otppopupresend: 'ओटीपी पुन: भेजें',
        otperror1: 'ओटीपी आवश्यक है',
        otperror2: 'कुछ गलत हो गया है। कृपया बाद में दोबारा प्रयास करें!',
        otptoastermsg: 'दिए गए मोबाइल नंबर पर ओटीपी भेजा गया है',
        formsuccess: 'सफलतापूर्वक!',
        term1:'मैं सहमत हूं कि मैंने',
        term2: 'को पढ़ और स्वीकार कर लिया है',
        termconditionlink:'नियम और शर्तों'
    },
    marathi: {
        title: 'सब ब्रोकर बना',
        namelbl: 'नाव',
        moblbl: 'मोबाइल नंबर',
        emaillbl: 'ईमेल',
        citylbl: 'शहर निवडा',
        statelbl: 'राज्य शोध',
        namelblerror1: 'अवैध नाव',
        namelblerror2: 'अपना नाम दर्ज करें',
        moblblerror1: 'आपले नांव लिहा',
        moblblerror2: '10 अंकी मोबाईल नंबर टाका',
        emaillblerror1: 'कृपया तुमचा ईमेल प्रविष्ट करा',
        emaillblerror2: 'अवैध ईमेल',
        citylblerror1: 'शहराची निवड आवश्यक',
        statelblerror1: 'राज्य निवड आवश्यक',
        sendotpbtn: 'ओटीपी पाठवा',
        termstitle: 'लक्ष द्या',
        termscontent: 'आम्ही हा डेटा केवळ संवादाच्या उद्देशाने संकलित करत आहोत आणि तो सुरक्षितपणे संग्रहित केला जाईल. आम्ही तुमच्या गोपनीयतेचे रक्षण करण्यासाठी वचनबद्ध आहोत. तुम्ही आम्हाला SMS/ Whatsapp/ Email/ Call द्वारे अपडेट पाठवण्याची परवानगी देत आहात आणि हे DND चे उल्लंघन मानले जाणार नाही.',
        termsbtn: 'ठिक आहे',
        otppopuptitle: 'कृपया अपना मोबाइल नंबर सत्यापित करने के लिए ओटीपी दर्ज करें',
        otppopupinfo: 'ओटीपी पाठवा',
        otppopuptimeremaining: 'बाकी वेळ:',
        otppopupbtn: 'कृपया ते प्रमाणित करा',
        otppopupresend: 'OTP पुन्हा पाठवा',
        otperror1: 'OTP आवश्यक आहे',
        otperror2: 'काहीतरी चूक झाली आहे. कृपया पुन्हा प्रयत्न करा!',
        otptoastermsg: 'दिलेल्या मोबाईल नंबरवर OTP पाठवला आहे',
        formsuccess: 'यशस्वीरित्या',
        term1:'मी सहमत आहे की मी',
        term2: 'वाचले आणि स्वीकारले',
        termconditionlink:'नियम आणि अटी'
    },
    gujarati: {
        title: 'સબ બ્રોકર બનો',
        namelbl: 'નામ',
        moblbl: 'મોબાઈલ નંબર ',
        emaillbl: 'ઈ મેઈલ આઈડી',
        citylbl: 'નજીકની શહેરની શાખા શોધો',
        statelbl: 'રાજ્ય શોધ',
        namelblerror1: 'અમાન્ય નામ',
        namelblerror2: 'તમારું નામ દાખલ કરો',
        moblblerror1: 'તમારું નામ લખો',
        moblblerror2: '10 અંકનો મોબાઈલ નંબર દાખલ કરો',
        emaillblerror1: 'કૃપા કરીને તમારો ઈમેલ દાખલ કરો',
        emaillblerror2: 'અમાન્ય ઇમેઇલ',
        citylblerror1: 'શહેરની પસંદગી જરૂરી છે',
        statelblerror1: 'રાજ્ય પસંદગી જરૂરી',
        sendotpbtn: 'ઓટીપી મોકલો',
        termstitle: 'ધ્યાન આપો',
        termscontent: 'અમે આ ડેટા માત્ર સંચાર હેતુઓ માટે એકત્રિત કરી રહ્યા છીએ અને તેને સુરક્ષિત રીતે સંગ્રહિત કરવામાં આવશે. અમે તમારી ગોપનીયતાના રક્ષણ માટે પ્રતિબદ્ધ છીએ. તમે અમને SMS/Whatsapp/Email/Col દ્વારા અપડેટ્સ મોકલવાની મંજૂરી આપો છો અને આને DNDનું ઉલ્લંઘન ગણવામાં આવશે નહીં.',
        termsbtn: 'બરાબર',
        otppopuptitle: 'તમારો મોબાઈલ નંબર ચકાસવા માટે કૃપા કરીને OTP દાખલ કરો',
        otppopupinfo: 'ઓટીપી મોકલો',
        otppopuptimeremaining: 'બાકી સમય:',
        otppopupbtn: 'કૃપા કરીને તેને માન્ય કરો',
        otppopupresend: 'OTP ફરીથી મોકલો',
        otperror1: 'OTP જરૂરી છે',
        otperror2: 'કંઈક ખોટું થયું છે. મહેરબાની કરીને ફરીથી પ્રયતન કરો!',
        otptoastermsg: 'આપેલા મોબાઈલ નંબર પર OTP મોકલવામાં આવ્યો છે',
        formsuccess: 'સફળતાપૂર્વક !',
        term1:'હું સંમત છું કે હું',
        term2: 'વાંચ્યું અને સ્વીકાર્યું',
        termconditionlink:'નિયમો અને શરત'
    },
    telagu: {
        title: 'సబ్ బ్రోకర్ అవుతాడు',
        namelbl: 'పేరు',
        moblbl: 'మొబైల్ నంబర్',
        emaillbl: 'ఇ-మెయిల్',
        citylbl: 'నగరాన్ని ఎంచుకోండి',
        statelbl: 'శోధన స్థితి',
        namelblerror1: 'చెల్లని పేరు',
        namelblerror2: 'మీ పేరు రాయుము, మీ పేరు రాయండిs',
        moblblerror1: 'చెల్లని మొబైల్ నంబర్',
        moblblerror2: '10 అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి',
        emaillblerror1: 'దయచేసి మీ ఇమెయిల్‌ని నమోదు చేయండి',
        emaillblerror2: 'చెల్లని ఇమెయిల్',
        citylblerror1: 'నగరం ఎంపిక అవసరం',
        statelblerror1: 'రాష్ట్ర ఎంపిక అవసరం',
        sendotpbtn: 'OTPని పంపండి',
        termstitle: 'శ్రద్ధ వహించండి',
        termscontent: 'మేము కమ్యూనికేషన్ ప్రయోజనాల కోసం మాత్రమే ఈ డేటాను సేకరిస్తున్నాము మరియు ఇది సురక్షితంగా నిల్వ చేయబడుతుంది. ',
        termsbtn: 'అలాగే',
        otppopuptitle: 'దయచేసి మీ మొబైల్ నంబర్‌ని ధృవీకరించడానికి OTPని నమోదు చేయండి',
        otppopupinfo: 'OTP పంపబడింది',
        otppopuptimeremaining: 'మిగిలి వున్న సమయం:',
        otppopupbtn: 'దయచేసి దానిని ధృవీకరించండి',
        otppopupresend: 'OTP ను మళ్ళీ పంపు',
        otperror1: 'OTP అవసరం',
        otperror2: 'ఏదో తప్పు జరిగింది. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి!',
        otptoastermsg: 'ఇచ్చిన మొబైల్ నంబర్‌కు OTP పంపబడింది',
        formsuccess: 'విజయవంతంగా!',
        term1:'నేను అంగీకరిస్తున్నాను',
        term2: 'చదివి అంగీకరించారు',
        termconditionlink:'నిబంధనలు మరియు షరతులు'
    },
    mutualDistributorhindi: {
        title: 'म्यूचुअल फंड एजेंट बने',
        namelbl: 'नाम',
        moblbl: 'मोबाइल नंबर',
        emaillbl: 'ईमेल',
        citylbl: 'शहर का चयन करें',
        statelbl: 'राज्य खोजें',
        namelblerror1: 'अमान्य नाम',
        namelblerror2: 'अपना नाम दर्ज करें',
        moblblerror1: 'अमान्य मोबाइल नंबर',
        moblblerror2: '10 अंकों का मोबाइल नंबर दर्ज करें',
        emaillblerror1: 'अपना ईमेल दर्ज करें',
        emaillblerror2: 'अमान्य ईमेल',
        citylblerror1: 'शहर का चयन आवश्यक है',
        statelblerror1: 'राज्य का चयन आवश्यक है',
        sendotpbtn: 'OTP भेजें',
        termstitle: 'ध्यान दें',
        termscontent: 'हम यह डेटा केवल संचार के उद्देश्य से ले रहे हैं और इसे सुरक्षित रूप से संग्रहीत किया जाएगा। हम आपकी गोपनीयता की रक्षा के लिए प्रतिबद्ध हैं, इससे सहमत होकर आप हमें एसएमएस/व्हाट्सएप/ईमेल/कॉल के माध्यम से अपडेट भेजने की अनुमति दे रहे हैं और इसे डीएनडी का उल्लंघन नहीं कहा जाएगा।',
        termsbtn: 'ठीक है',
        otppopuptitle: 'कृपया अपना मोबाइल नंबर सत्यापित करने के लिए ओटीपी दर्ज करें',
        otppopupinfo: 'ओटीपी भेज दिया गया है',
        otppopuptimeremaining: 'ओटीपी फिर से भेजें:',
        otppopupbtn: 'सत्यापित करें',
        otppopupresend: 'ओटीपी पुन: भेजें',
        otperror1: 'ओटीपी आवश्यक है',
        otperror2: 'कुछ गलत हो गया है। कृपया बाद में दोबारा प्रयास करें!',
        otptoastermsg: 'दिए गए मोबाइल नंबर पर ओटीपी भेजा गया है',
        formsuccess: 'सफलतापूर्वक!',
        term1:'मैं सहमत हूं कि मैंने',
        term2: 'को पढ़ और स्वीकार कर लिया है',
        termconditionlink:'नियम और शर्तों'
    }


};

const SubBrokerLanguageContent = {
    getContent: function (lang, field, engmsg) {
        return (language[lang] && language[lang][field]) || engmsg;
    }
}

export default SubBrokerLanguageContent;